/** @type {import('tailwindcss').Config} */

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      'sans': ['ui-sans-serif', 'system-ui'],
     },
    extend: {
      backgroundImage: {
        'hero-pattern': "url('/backgrounds/back-ground-welcome.png')",
        'hero-pattern2': "url('/backgrounds/back-ground2.png')",
        'foro-pattern1': "url('/foros-cover/fondo1.png')",
        'foro-pattern2': "url('/foros-cover/fondo2.png')",
        'foro-pattern3': "url('/foros-cover/fondo3.png')",
        'foro-pattern4': "url('/foros-cover/fondo4.png')",
        'foro-pattern5': "url('/foros-cover/fondo5.png')",
        'foro-pattern6': "url('/foros-cover/fondo6.png')",
        'foro-pattern7': "url('/foros-cover/fondo7.png')",
        'foro-pattern8': "url('/foros-cover/fondo8.png')",
        'foro-pattern9': "url('/foros-cover/fondo9.png')",
        'foro-terror': "url('/backgrounds/foro-terror.png')",
        'foro-aventura': "url('/backgrounds/foro-aventura.png')",
        'foro-ciencia-ficcion': "url('/backgrounds/foro-ciencia-ficcion.png')",
        'foro-contemporaneo': "url('/backgrounds/foro-contemporaneo.png')",
        'foro-fantasia': "url('/backgrounds/foro-fantasia.png')",
        'foro-juvenil': "url('/backgrounds/foro-juvenil.png')",
        'foro-novela': "url('/backgrounds/foro-novela.png')",
        'foro-poesia': "url('/backgrounds/foro-poesia.png')",
        'foro-policiaco': "url('/backgrounds/foro-policiaco.png')",
        'foro-romance': "url('/backgrounds/foro-romance.png')",
        'foro-sup-personal': "url('/backgrounds/foro-sup-personal.png')",
      },
    },
    fontFamily: {
      playwrite: ['Playwrite DK Uloopet', 'serif'],
      poppins: ['Poppins', 'serif'],
      merriweather: ['Merriweather', 'serif'],
    },
    colors: {
      'indigo-lighter': '#f7dad3',
      'indigo': '#f07170',
      'indigo-dark': '#be3e3d',
      'white': '#ffffff',
      'red': '#be3e3d',
      'black': '#000000',
      'yellow': '#e8aa77',
      'sky-light': '#38b6ff',
      'blue-dark': '#004aad',
      'blue': '#6aa9e9',
      'blue-true': '#318ce7',
      'gray': '#aaaaaa',
      'creme': '#faf5ea',
      'green-creme': '#eef8eb',
      'orange': '#ff9376',
      'orange-light': '#ffd8cc',
      'blue-jordy': '#8db9e4',
      'green': '#8daaa6',
      'green-normal': '#73c883',
      'green-true': '#4da768',
      'blue-gray': '#d5dae3',
      'blue-creme': '#dfe6f2',
      'purple-creme': '#e8e0eb',
      'white-gray': '#f4f4f4',
      'dark-gray': '#474B4e',
      'red-light': '#ffd1d2',
      'red-dark': '#8b0000',
    }

  },
  plugins: [],
}

